### ISSUE TITLE
submit_faq view is broken

### ISSUE THREAD

**Issue by cyberdelia** [howiworkdaily/django-faq#3]
submit_faq view don't link newly created Question to a Topic and so don't work anymore.

**Comment by mikek** [comment]
trying to import the fixture gives nearly the same error:
IntegrityError: faq_question.topic_id may not be NULL

**Comment by montylounge** [comment]
I'll review asap. Sorry for delay.

**Comment by mdornseif** [comment]
This is fixed by http://github.com/alexhayes/django-faq/commit/ed366f4b385d140ebdb628f780f4ba773058e9b2#diff-0 (default value)

or

http://github.com/mikek/django-faq/commit/9d09468af87c96aa47fb6e8d000e81ea457ba7c0 (additional form field).
