### ISSUE TITLE
Fixture data faq_test_data.json fails to load

### ISSUE THREAD

**Issue by gvwilson** [howiworkdaily/django-faq#7]
- Python2.7 and Django 1.3 on Ubuntu 10.10 (Maverick Meerkat).
- Cloned git repo.
- cd django-faq/example
- python manage.py syncdb (created admin user when asked)
- python manage.py loaddata ../faq/fixtures/faq_test_data.json produces:

Problem installing fixture '../faq/fixtures/faq_test_data.json': Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/core/management/commands/loaddata.py", line 169, in handle
    for obj in objects:
  File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/core/serializers/json.py", line 35, in Deserializer
    for obj in PythonDeserializer(simplejson.load(stream), **options):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/core/serializers/python.py", line 93, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/options.py", line 289, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, name))
FieldDoesNotExist: Topic has no field named 'sort_order'

A possibly related problem (?).  After this failure, 'rm faq.db' and 'python manage.py syncdb' to create a fresh one (just in case), then:
- python manage.py runserver
- point browser at http://127.0.0.1:8000/
- get error page:

TemplateSyntaxError at /

'faqtags' is not a valid tag library: Template library faqtags not found, tried django.templatetags.faqtags,django.contrib.admin.templatetags.faqtags

However, ~/django-faq/faq/templatetags/faqtags.py (and .../**init**.py) _do_ exist.

**Comment by zuzelvp** [comment]
Could it be that example you cloned from the github repo and the django_faq you installed with pip are not compatible? Check if there is a sort_order field in the models.py of the django_faq that got installed (like here: https://github.com/howiworkdaily/django-faq/blob/master/faq/models.py#L14). I will recommend you to install django_faq with:

pip install -e git://github.com/howiworkdaily/django-faq.git#egg=django_faq

instead of:

pip install django_faq

## 

Thanks,
    Zuzel

**Comment by zuzelvp** [comment]
Yes the Topic model installed with pip install django_faq looks quite different: http://pastie.org/2513969

**Comment by gvwilson** [comment]
Zuzel's analysis is correct --- a change to the docs (and a warning about the other similarly-named package) is on its way.
